// Generated by CoffeeScript 1.7.1
(function() {
  var PSD, key, utils, value;

  PSD = Framer.Importer.load("imported/pickup");

  for (key in PSD) {
    value = PSD[key];
    PSD[key].originalFrame = PSD[key].frame;
  }

  Framer.Defaults.Animation = {
    "curve": "ease-out",
    "time": 0.2
  };

  utils = {
    fadeIn: function(view, delay) {
      return view.animate({
        properties: {
          opacity: 1
        },
        delay: delay
      });
    },
    fadeOut: function(view, delay) {
      return view.animate({
        properties: {
          opacity: 0
        },
        delay: delay
      });
    },
    originalPos: function(view, delay) {
      return view.animate({
        properties: {
          x: view.originalFrame.x,
          y: view.originalFrame.y
        },
        delay: delay
      });
    },
    moveX: function(view, distance, delay) {
      return view.animate({
        properties: {
          x: distance
        },
        delay: delay
      });
    }
  };

  PSD.phone.properties = {
    "width": 640,
    "height": 1136,
    "clip": true
  };

  PSD.windows.opacity = 0;

  PSD.grayside.y = 1136;

  utils.fadeIn(PSD.windows, 0.5);

  utils.originalPos(PSD.grayside, 0.4);

  PSD.windows.on(Events.Click, function() {
    utils.fadeOut(PSD.windows);
    utils.moveX(PSD.sky1, -300);
    PSD.grayside.animate({
      properties: {
        scale: 2
      }
    });
    return utils.moveX(PSD.slide2, 0, 0.25);
  });

}).call(this);
