// Generated by CoffeeScript 1.7.1
(function() {
  var PSD, key, switchSlide, value;

  PSD = Framer.Importer.load("imported/pickup");

  for (key in PSD) {
    value = PSD[key];
    PSD[key].originalFrame = PSD[key].frame;
  }

  Framer.Defaults.Animation = {
    "curve": "ease-out",
    "time": 0.2
  };

  PSD.phone.properties = {
    "width": 640,
    "height": 1136,
    "clip": true
  };

  switchSlide = function(slideNum) {
    switch (slideNum) {
      case 0:
        common.originalPos(PSD.slide2);
        PSD.grayside.y = 1136;
        PSD.sky1.hueRotate = 50;
        PSD.windows.opacity = 0;
        common.fadeIn(PSD.windows, 0.5);
        common.originalPos(PSD.grayside, 0.4);
        return common.originalHue(PSD.sky1, 0.5);
      case 1:
        common.fadeOut(PSD.windows);
        common.moveX(PSD.sky1, -300);
        common.moveX(PSD.slide2, 0);
        return PSD.sky1.animate({
          properties: {
            hueRotate: 0
          }
        });
    }
  };

  PSD.windows.on(Events.Click, function() {
    return switchSlide(1);
  });

  PSD.slide2.on(Events.Click, function() {
    return switchSlide(0);
  });

  switchSlide(0);

}).call(this);
